site_name: compas_nest
site_description: 2D irregular nesting (OpenNest) for COMPAS
repo_url: https://github.com/petrasvestartas/compas_nest
site_author: Petras Vestartas

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - content.code.copy

nav:
  - Home: index.md
  - Installation: installation.md
  - Examples: examples.md
  - API Reference: reference.md
  - Credits: credits.md
  - Changelog: changelog.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_heading: true
            show_source: true
            members_order: source

markdown_extensions:
  - admonition
  - markdown_callouts
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path: ["."]
      check_paths: true
  - toc:
      permalink: true
